browser:
  browserName: CHROME
  browser.attachscreenshot: true
  browser.headless: true
  browser.webelement.timeout: 60
environment:
  appUrl: http://146.59.32.4/index.php
  basketUrl: http://146.59.32.4/index.php?controller=cart&action=show
  address: Hogwarts 1
  postcode: 00-000
  city: Hogsmeade
  payment: Payments by check
  shippingMethod: My carrier
